<a href="https://colab.research.google.com/github/matari18/ml/blob/main/LogReg_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Логистическая регрессия

Обучим логистическую регрессию для предсказания того, откликнется клиент  
на рекламное предложение (target = 1) или нет (target = 0).

## Подлючение библиотек, загрузка и обзор данных

In [23]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [24]:
data = pd.read_csv('https://raw.githubusercontent.com/evgpat/edu_stepik_practical_ml/main/datasets/clients_data.csv')

In [25]:
data.head()

AGE  SOCSTATUS_WORK_FL  SOCSTATUS_PENS_FL  GENDER  CHILD_TOTAL  DEPENDANTS  \
0   49                  1                  0       1            2           1   
1   32                  1                  0       1            3           3   
2   52                  1                  0       1            4           0   
3   39                  1                  0       1            1           1   
4   30                  1                  0       0            0           0   

   PERSONAL_INCOME  LOAN_NUM_TOTAL  LOAN_NUM_CLOSED  LOAN_DLQ_NUM  TARGET  
0           5000.0               1                1             2       0  
1          12000.0               1                1             1       0  
2           9000.0               2                1             0       0  
3          25000.0               1                1             3       0  
4          12000.0               2                1             2       0

In [26]:
from sklearn.model_selection import train_test_split

X = data.drop('TARGET', axis=1)
y = data['TARGET']

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, train_size=0.7, random_state=123)

## Практика

**Задание**  
Выведите на экран количество объектов каждого класса. Сколько процентов объектов относятся к положительному классу?  
Ответ округлите до целого числа (например, если доля объектов положительного класса равна 0.412, в ответ запишите 41,  
имея в виду 41 процент).

In [27]:
len(y[y==0])

13411

In [28]:
len(y[y==1])

1812

In [29]:
round(len(y[y==1])/len(y), 2) * 100


12.0

Обучим логистическую регрессию с параметрами по умолчанию.

In [30]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [31]:
lr.fit(Xtrain, ytrain)

prediction = lr.predict(Xtest)

Метрику accuracy не стоит использовать при сильном дисбалансе классов. Поэтому посчитайте f1_score для оценки качества модели на тестовых данных.

f1_score принимает значения от 0 до 1. Чем ближе к 1, тем лучше модель.

In [32]:
from sklearn.metrics import f1_score

f1_score(ytest, prediction)

0.0

**Вопрос**  
Чему равен `f1_score`?

Удивительно, да?

Давайте разберемся, почему качество такое низкое.

Предскажем вероятности классов с помощью обученной логистической регрессии на тестовых данных.

In [33]:
probs_test = lr.predict_proba(Xtest)

probs_test[:10]

array([[0.86331972, 0.13668028],
       [0.86305957, 0.13694043],
       [0.80967732, 0.19032268],
       [0.73110167, 0.26889833],
       [0.87780414, 0.12219586],
       [0.96122864, 0.03877136],
       [0.95965491, 0.04034509],
       [0.96560659, 0.03439341],
       [0.92114871, 0.07885129],
       [0.9349701 , 0.0650299 ]])

По вероятностям видно, что вероятности отнесения к положительному классу очень низкие.

Попробуем изменить порог для перевода вероятности в классы.

**Вопрос**  
Чему равен `f1_score`, если все объекты с вероятностью не меньшей 0.1, относить к положительному классу?

Ответ округлите до сотых.

In [34]:
new_prediction = (probs_test[:,1]>=0.1)*1

In [35]:
f1_score(ytest, new_prediction)

0.2469521725539231

У обученной модели можно посмотреть веса (как и в линейной регрессии).  
Выведем на экран веса модели (`model.coef_`, `model.intercept_`).

In [36]:
lr.coef_, lr.intercept_

(array([[-5.55214705e-02, -7.90868782e-04, -4.28172545e-04,
         -1.07248154e-03, -1.34958177e-03, -4.95807875e-04,
          1.13131722e-05, -1.80011616e-03, -1.26843809e-03,
         -1.45283567e-05]]),
 array([-0.00115086]))

Создайте `pd.DataFrame`, где в первом столбце стоят названия признаков, а во втором - их веса (так удобнее анализировать результат).  
Отсортируйте таблицу по убыванию весов.

**Вопрос**  
Какой признак имеет наибольший положительный вес?

In [37]:
features = pd.DataFrame({'coef': lr.coef_[0], 'value': lr.feature_names_in_}).sort_values(by = 'coef', ascending = False).set_index('value')

In [38]:
features

coef
value                      
PERSONAL_INCOME    0.000011
LOAN_DLQ_NUM      -0.000015
SOCSTATUS_PENS_FL -0.000428
DEPENDANTS        -0.000496
SOCSTATUS_WORK_FL -0.000791
GENDER            -0.001072
LOAN_NUM_CLOSED   -0.001268
CHILD_TOTAL       -0.001350
LOAN_NUM_TOTAL    -0.001800
AGE               -0.055521

## Бонус

**Задание 1**  
Подберите порог для перевода вероятностей в классы, дающий максимальное значение `f1_score`.

In [39]:
f1 = 0
for thr in np.arange(0, 1, 0.01):
     new_prediction = (probs_test[:,1]>=thr)*1
     new_f1 = f1_score(ytest, new_prediction)
     if new_f1 >= f1:
         f1 = new_f1
f1

0.2469521725539231

**Задание 2**  
Во вложенном цикле подберите одновременно коэффициент регуляризации `C` у логистической регрессии и порог для перевода вероятностей в классы, дающие максимальное значение `f1_score`.

По-хорошему, чтобы не переобучиться, эти величины надо подбирать не по тесту, а по отдельной выборке.

Поэтому разобъем данные изначально на три части: `Xtrain`, `Xval`, `Xtest`.

*   В цикле при подборе `С` и порога будем обучаться по `Xtrain`, а предсказывать и измерять качество по `Xval`.

*   Качество итоговой модели с найденными `C` и порогом измерьте по `Xtest`.

Так не переобучимся!


In [43]:
Xtrain_new, Xval, ytrain_new, yval = train_test_split(Xtrain, ytrain, train_size=0.7, random_state=123)

best_с = 1.0
best_thr = 0
best_f1 = 0
for thr in np.arange(0, 1, 0.01):
    for c in np.arange(0.01, 1, 0.01):
        lr = LogisticRegression(C=c)
        lr.fit(Xtrain_new, ytrain_new)
        prediction = lr.predict_proba(Xval)
        new_prediction = (prediction[:,1]>=thr)*1
        new_f1 = f1_score(yval, new_prediction)
        if new_f1 >= best_f1:
            best_f1 = new_f1
            best_c = c
            best_thr = thr

best_f1, best_c, best_thr

(0.23018677435638565, 0.99, 0.12)

In [44]:
model = LogisticRegression(C=best_c)
model.fit(Xtrain, ytrain) # обучаемся на всех тренировочных данных
prediction = model.predict_proba(Xtest)

classes = (prediction[:,1]>=best_thr)*1 # переведите полученные вероятности в классы по найденному порогу

In [45]:
# вычислите значение f1_score на тестовых данных
f1_score(ytest, classes)

0.24345930232558144